# Generated by Django 2.2 on 2020-11-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_dash', '0002_auto_20201108_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
