# Generated by Django 2.2 on 2020-11-09 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_dash', '0003_quote_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='user_likes',
            new_name='likes',
        ),
    ]
